function zdot = lean_heading(I11,I22,I33,V,Vdot,df,dr,g,h,m,phi,phidot,theta_F,theta_R,theta_Fdot,theta_Rdot)
%LEAN_HEADING
%    ZDOT = LEAN_HEADING(I11,I22,I33,V,Vdot,DF,DR,G,H,M,PHI,PHIDOT,theta_F,theta_R,theta_Fdot,theta_Rdot)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    12-Jun-2024 18:29:12

t2 = cos(phi);
t3 = cos(theta_F);
t4 = cos(theta_R);
t5 = sin(phi);
t6 = sin(theta_F);
t7 = sin(theta_R);
t8 = tan(theta_R);
t9 = df+dr;
t11 = V.^2;
t12 = df.^2;
t13 = dr.^2;
t14 = h.^2;
t10 = abs(t4);
t15 = t2.^2;
t16 = t2.^3;
t18 = t2.^5;
t19 = t3.^2;
t20 = t4.^2;
t21 = t4.^3;
t23 = t4.^5;
t17 = t15.^2;
t22 = t20.^2;
t24 = 1.0./t10;
t25 = -t20;
t26 = t15.*t20;
t27 = t25+t26+1.0;
t28 = sqrt(t27);
t29 = t28.^3;
et1 = Vdot.*h.*m.*t2.*t7.*t12.*t19+V.*h.*m.*t2.*t4.*t13.*theta_Fdot-V.*h.*m.*t2.*t13.*t21.*theta_Fdot.*2.0+V.*h.*m.*t2.*t13.*t23.*theta_Fdot+V.*h.*m.*t13.*t16.*t21.*theta_Fdot.*2.0-V.*h.*m.*t13.*t16.*t23.*theta_Fdot.*2.0+V.*h.*m.*t13.*t18.*t23.*theta_Fdot+I22.*t2.*t5.*t11.*t21.*t24.*t28-I22.*t2.*t5.*t11.*t23.*t24.*t28-I33.*t2.*t5.*t11.*t21.*t24.*t28+I33.*t2.*t5.*t11.*t23.*t24.*t28+I22.*t5.*t11.*t16.*t23.*t24.*t28-I33.*t5.*t11.*t16.*t23.*t24.*t28+g.*h.*m.*t5.*t12.*t19.*t29+g.*h.*m.*t5.*t13.*t19.*t29+Vdot.*df.*dr.*h.*m.*t2.*t7.*t19+V.*df.*dr.*h.*m.*t2.*t4.*theta_Fdot-V.*df.*dr.*h.*m.*t2.*t21.*theta_Fdot.*2.0+V.*df.*dr.*h.*m.*t2.*t23.*theta_Fdot+V.*df.*dr.*h.*m.*t16.*t21.*theta_Fdot.*2.0-V.*df.*dr.*h.*m.*t16.*t23.*theta_Fdot.*2.0+V.*df.*dr.*h.*m.*t18.*t23.*theta_Fdot;
et2 = df.*dr.*g.*h.*m.*t5.*t19.*t29.*2.0+Vdot.*h.*m.*t2.*t3.*t4.*t6.*t13-Vdot.*h.*m.*t2.*t3.*t6.*t13.*t21.*2.0+Vdot.*h.*m.*t2.*t3.*t6.*t13.*t23+Vdot.*h.*m.*t3.*t6.*t13.*t16.*t21.*2.0-Vdot.*h.*m.*t2.*t7.*t12.*t19.*t20.*2.0-Vdot.*h.*m.*t3.*t6.*t13.*t16.*t23.*2.0+Vdot.*h.*m.*t2.*t7.*t12.*t19.*t22+Vdot.*h.*m.*t3.*t6.*t13.*t18.*t23+Vdot.*h.*m.*t7.*t12.*t16.*t19.*t20.*2.0-Vdot.*h.*m.*t7.*t12.*t16.*t19.*t22.*2.0+Vdot.*h.*m.*t7.*t12.*t18.*t19.*t22+V.*h.*m.*t4.*t12.*t16.*t19.*theta_Rdot-V.*h.*m.*t12.*t16.*t19.*t21.*theta_Rdot+V.*h.*m.*t12.*t18.*t19.*t21.*theta_Rdot+I22.*t2.*t4.*t5.*t11.*t19.*t24.*t28-I33.*t2.*t4.*t5.*t11.*t19.*t24.*t28-I22.*t2.*t5.*t11.*t19.*t21.*t24.*t28.*3.0+I22.*t2.*t5.*t11.*t19.*t23.*t24.*t28.*2.0+I33.*t2.*t5.*t11.*t19.*t21.*t24.*t28.*3.0;
et3 = I33.*t2.*t5.*t11.*t19.*t23.*t24.*t28.*-2.0+I22.*t5.*t11.*t16.*t19.*t21.*t24.*t28-I22.*t5.*t11.*t16.*t19.*t23.*t24.*t28.*2.0-I33.*t5.*t11.*t16.*t19.*t21.*t24.*t28+I33.*t5.*t11.*t16.*t19.*t23.*t24.*t28.*2.0+df.*h.*m.*t3.*t6.*t11.*t26.*t29+dr.*h.*m.*t3.*t6.*t11.*t26.*t29+g.*h.*m.*t5.*t12.*t19.*t25.*t29+g.*h.*m.*t5.*t12.*t19.*t26.*t29+g.*h.*m.*t5.*t13.*t19.*t25.*t29+g.*h.*m.*t5.*t13.*t19.*t26.*t29+m.*t2.*t5.*t11.*t14.*t21.*t24.*t28-m.*t2.*t5.*t11.*t14.*t23.*t24.*t28+m.*t5.*t11.*t14.*t16.*t23.*t24.*t28+Vdot.*df.*dr.*h.*m.*t2.*t3.*t4.*t6-Vdot.*df.*dr.*h.*m.*t2.*t3.*t6.*t21.*2.0+Vdot.*df.*dr.*h.*m.*t2.*t3.*t6.*t23+Vdot.*df.*dr.*h.*m.*t3.*t6.*t16.*t21.*2.0-Vdot.*df.*dr.*h.*m.*t2.*t7.*t19.*t20.*2.0;
et4 = Vdot.*df.*dr.*h.*m.*t3.*t6.*t16.*t23.*-2.0+Vdot.*df.*dr.*h.*m.*t2.*t7.*t19.*t22+Vdot.*df.*dr.*h.*m.*t3.*t6.*t18.*t23+Vdot.*df.*dr.*h.*m.*t7.*t16.*t19.*t20.*2.0-Vdot.*df.*dr.*h.*m.*t7.*t16.*t19.*t22.*2.0+Vdot.*df.*dr.*h.*m.*t7.*t18.*t19.*t22+V.*df.*dr.*h.*m.*t4.*t16.*t19.*theta_Rdot-V.*df.*dr.*h.*m.*t16.*t19.*t21.*theta_Rdot+V.*df.*dr.*h.*m.*t18.*t19.*t21.*theta_Rdot-df.*dr.*g.*h.*m.*t5.*t19.*t20.*t29.*2.0+df.*dr.*g.*h.*m.*t5.*t19.*t26.*t29.*2.0+V.*h.*m.*phidot.*t5.*t7.*t12.*t19.*t26-V.*h.*m.*t2.*t3.*t6.*t7.*t13.*theta_Rdot-df.*h.*m.*t4.*t7.*t11.*t15.*t19.*t29-dr.*h.*m.*t4.*t7.*t11.*t15.*t19.*t29+m.*t2.*t4.*t5.*t11.*t14.*t19.*t24.*t28-m.*t2.*t5.*t11.*t14.*t19.*t21.*t24.*t28.*3.0+m.*t2.*t5.*t11.*t14.*t19.*t23.*t24.*t28.*2.0;
et5 = m.*t5.*t11.*t14.*t16.*t19.*t21.*t24.*t28-m.*t5.*t11.*t14.*t16.*t19.*t23.*t24.*t28.*2.0+V.*df.*dr.*h.*m.*phidot.*t5.*t7.*t19.*t26-V.*df.*dr.*h.*m.*t2.*t3.*t6.*t7.*theta_Rdot+V.*h.*m.*phidot.*t3.*t5.*t6.*t13.*t15.*t21-V.*h.*m.*phidot.*t3.*t5.*t6.*t13.*t15.*t23+V.*h.*m.*phidot.*t3.*t5.*t6.*t13.*t17.*t23-V.*h.*m.*phidot.*t5.*t7.*t12.*t15.*t19.*t22+V.*h.*m.*phidot.*t5.*t7.*t12.*t17.*t19.*t22+V.*h.*m.*t2.*t3.*t6.*t7.*t13.*t20.*theta_Rdot+V.*h.*m.*t3.*t6.*t7.*t13.*t16.*t25.*theta_Rdot-I22.*t2.*t3.*t5.*t6.*t7.*t11.*t20.*t24.*t28.*2.0+I22.*t2.*t3.*t5.*t6.*t7.*t11.*t22.*t24.*t28.*2.0+I33.*t2.*t3.*t5.*t6.*t7.*t11.*t20.*t24.*t28.*2.0-I33.*t2.*t3.*t5.*t6.*t7.*t11.*t22.*t24.*t28.*2.0-I22.*t3.*t5.*t6.*t7.*t11.*t16.*t22.*t24.*t28.*2.0;
et6 = I33.*t3.*t5.*t6.*t7.*t11.*t16.*t22.*t24.*t28.*2.0+V.*df.*dr.*h.*m.*phidot.*t3.*t5.*t6.*t15.*t21-V.*df.*dr.*h.*m.*phidot.*t3.*t5.*t6.*t15.*t23+V.*df.*dr.*h.*m.*phidot.*t3.*t5.*t6.*t17.*t23-V.*df.*dr.*h.*m.*phidot.*t5.*t7.*t15.*t19.*t22+V.*df.*dr.*h.*m.*phidot.*t5.*t7.*t17.*t19.*t22+V.*df.*dr.*h.*m.*t2.*t3.*t6.*t7.*t20.*theta_Rdot+V.*df.*dr.*h.*m.*t3.*t6.*t7.*t16.*t25.*theta_Rdot-m.*t2.*t3.*t5.*t6.*t7.*t11.*t14.*t20.*t24.*t28.*2.0+m.*t2.*t3.*t5.*t6.*t7.*t11.*t14.*t22.*t24.*t28.*2.0-m.*t3.*t5.*t6.*t7.*t11.*t14.*t16.*t22.*t24.*t28.*2.0;
zdot = [(1.0./t9.^2.*1.0./t28.^5.*(et1+et2+et3+et4+et5+et6))./(t19.*(I11+m.*t14));-(V.*(t8-tan(theta_F)).*1.0./sqrt(t15+t8.^2))./t9];
end
