function zdot = lean_heading(I11,I22,I33,V,Vdot,df,dr,g,h,m,phi,phidot,psi,theta_F,theta_R,theta_Fdot,theta_Rdot)
%LEAN_HEADING
%    ZDOT = LEAN_HEADING(I11,I22,I33,V,Vdot,DF,DR,G,H,M,PHI,PHIDOT,PSI,theta_F,theta_R,theta_Fdot,theta_Rdot)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    12-Jun-2024 23:14:51

t2 = cos(phi);
t3 = cos(psi);
t4 = sin(phi);
t5 = sin(psi);
t6 = tan(theta_F);
t7 = tan(theta_R);
t8 = df+dr;
t9 = V.^2;
t10 = h.^2;
t11 = t2.^2;
t12 = t2.^3;
t13 = t6.^2;
t14 = t7.^2;
t15 = 1.0./t8;
t16 = t15.^2;
t17 = t11+t14;
t18 = 1.0./t17;
t19 = 1.0./sqrt(t17);
t20 = t19.^3;
et1 = g.*h.*m.*t4+Vdot.*h.*m.*t2.*t7.*t19+V.*h.*m.*t12.*t20.*theta_Rdot.*1.0./cos(theta_R).^2+I22.*t2.*t4.*t9.*t13.*t16.*t18+I22.*t2.*t4.*t9.*t14.*t16.*t18-I33.*t2.*t4.*t9.*t13.*t16.*t18-I33.*t2.*t4.*t9.*t14.*t16.*t18+h.*m.*t6.*t9.*t11.*t15.*t18-h.*m.*t7.*t9.*t11.*t15.*t18+Vdot.*dr.*h.*m.*t2.*t6.*t15.*t19-Vdot.*dr.*h.*m.*t2.*t7.*t15.*t19+V.*dr.*h.*m.*t2.*t15.*t19.*theta_Fdot-V.*dr.*h.*m.*t12.*t15.*t20.*theta_Rdot+V.*h.*m.*phidot.*t4.*t7.*t11.*t20-I22.*t2.*t4.*t6.*t7.*t9.*t16.*t18.*2.0+I33.*t2.*t4.*t6.*t7.*t9.*t16.*t18.*2.0+m.*t2.*t4.*t9.*t10.*t13.*t16.*t18+m.*t2.*t4.*t9.*t10.*t14.*t16.*t18+V.*dr.*h.*m.*t2.*t13.*t15.*t19.*theta_Fdot-V.*dr.*h.*m.*t12.*t14.*t15.*t20.*theta_Rdot-m.*t2.*t4.*t6.*t7.*t9.*t10.*t16.*t18.*2.0;
et2 = -V.*dr.*h.*m.*t2.*t6.*t7.^3.*t15.*t20.*theta_Rdot+V.*dr.*h.*m.*phidot.*t4.*t6.*t11.*t15.*t20-V.*dr.*h.*m.*phidot.*t4.*t7.*t11.*t15.*t20-V.*dr.*h.*m.*t2.*t6.*t7.*t15.*t20.*theta_Rdot;
zdot = [V.*t19.*(t2.*t3-t5.*t7);V.*t19.*(t2.*t5+t3.*t7);V.*t15.*t19.*(t6-t7);(et1+et2)./(I11+m.*t10)];
end
