function M = Mass_matrix_M(I11,I22,I33,df,dr,h,m,phi,theta_F,theta_R)
%Mass_matrix_M
%    M = Mass_matrix_M(I11,I22,I33,DF,DR,H,m,PHI,theta_F,theta_R)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    22-May-2024 12:31:19

t2 = cos(phi);
t3 = cos(theta_F);
t4 = cos(theta_R);
t5 = sin(phi);
t6 = sin(theta_F);
t7 = sin(theta_R);
t8 = theta_R.*-1.0;
t10 = df+dr;
t11 = df.^2;
t12 = dr.^2;
t13 = h.^2;
t14 = t2.^2;
t15 = t3.^2;
t16 = t4.^2;
t17 = t5.^2;
t18 = 1.0./t3;
t19 = 1.0./t4.^5;
t20 = t8+theta_F;
t22 = df.*t3.*t7;
t23 = dr.*t4.*t6;
t24 = 1.0./t10;
t21 = sin(t20);
t25 = t16.^(5.0./2.0);
t27 = t22+t23;
t26 = 1.0./t21;
et1 = t18.*t19.*t24.*t25.*t26.*1.0./sqrt(-t17+t7.^2.*t17+1.0);
et2 = I22.*t15+I22.*t16-I22.*t14.*t15.*1.0-I22.*t14.*t16.*1.0-I22.*t15.*t16.*2.0+I33.*t14.*t15+I33.*t14.*t16+m.*t11.*t15+m.*t12.*t16+m.*t13.*t15+m.*t13.*t16+m.*t22.*t23.*2.0+I22.*t14.*t15.*t16.*2.0-I33.*t14.*t15.*t16.*2.0-m.*t11.*t15.*t16.*1.0-m.*t13.*t14.*t15.*1.0-m.*t12.*t15.*t16.*1.0-m.*t13.*t14.*t16.*1.0-m.*t13.*t15.*t16.*2.0-I22.*t3.*t4.*t6.*t7.*2.0+m.*t11.*t14.*t15.*t16+m.*t12.*t14.*t15.*t16+m.*t13.*t14.*t15.*t16.*2.0-m.*t3.*t4.*t6.*t7.*t13.*2.0+I22.*t3.*t4.*t6.*t7.*t14.*2.0-I33.*t3.*t4.*t6.*t7.*t14.*2.0+df.*dr.*m.*t14.*t15.*t16.*2.0+m.*t3.*t4.*t6.*t7.*t13.*t14.*2.0+df.*h.*m.*t2.*t3.*t5.*t6.*t16.*2.0-df.*h.*m.*t2.*t4.*t5.*t7.*t15.*2.0+dr.*h.*m.*t2.*t3.*t5.*t6.*t16.*2.0-dr.*h.*m.*t2.*t4.*t5.*t7.*t15.*2.0;
et3 = -1.0;
M = reshape([1.0,0.0,0.0,0.0,0.0,0.0,et1.*et2.*et3,h.*m.*t2.*t18.*t19.*t24.*t25.*t27.*1.0./sqrt(-t16+t14.*t16+1.0),0.0,0.0,0.0,h.*m.*t2.*t26.*t27.*1.0,-I11-m.*t13,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0],[5,5]);
end
