function phiddot = phiddot(I11,I22,I33,V,Vdot,df,dr,g,h,m,phi,phidot,theta_F,theta_R,theta_Fdot,theta_Rdot)
%PHIDDOT
%    PHIDDOT = PHIDDOT(I11,I22,I33,V,Vdot,DF,DR,G,H,M,PHI,PHIDOT,theta_F,theta_R,theta_Fdot,theta_Rdot)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    02-Jul-2024 12:45:30

t2 = cos(phi);
t3 = sin(phi);
t4 = tan(theta_F);
t5 = tan(theta_R);
t6 = df+dr;
t7 = V.^2;
t8 = h.^2;
t9 = t2.^2;
t10 = t2.^3;
t11 = t4.^2;
t12 = t5.^2;
t13 = 1.0./t6;
t14 = t13.^2;
t15 = t9+t12;
t16 = 1.0./t15;
t17 = 1.0./sqrt(t15);
t18 = t17.^3;
et1 = g.*h.*m.*t3+Vdot.*h.*m.*t2.*t5.*t17+V.*h.*m.*t10.*t18.*theta_Rdot.*1.0./cos(theta_R).^2+I22.*t2.*t3.*t7.*t11.*t14.*t16+I22.*t2.*t3.*t7.*t12.*t14.*t16-I33.*t2.*t3.*t7.*t11.*t14.*t16-I33.*t2.*t3.*t7.*t12.*t14.*t16+h.*m.*t4.*t7.*t9.*t13.*t16-h.*m.*t5.*t7.*t9.*t13.*t16+Vdot.*dr.*h.*m.*t2.*t4.*t13.*t17-Vdot.*dr.*h.*m.*t2.*t5.*t13.*t17+V.*dr.*h.*m.*t2.*t13.*t17.*theta_Fdot-V.*dr.*h.*m.*t10.*t13.*t18.*theta_Rdot+V.*h.*m.*phidot.*t3.*t5.*t9.*t18-I22.*t2.*t3.*t4.*t5.*t7.*t14.*t16.*2.0+I33.*t2.*t3.*t4.*t5.*t7.*t14.*t16.*2.0+m.*t2.*t3.*t7.*t8.*t11.*t14.*t16+m.*t2.*t3.*t7.*t8.*t12.*t14.*t16+V.*dr.*h.*m.*t2.*t11.*t13.*t17.*theta_Fdot-V.*dr.*h.*m.*t10.*t12.*t13.*t18.*theta_Rdot-m.*t2.*t3.*t4.*t5.*t7.*t8.*t14.*t16.*2.0;
et2 = -V.*dr.*h.*m.*t2.*t4.*t5.^3.*t13.*t18.*theta_Rdot+V.*dr.*h.*m.*phidot.*t3.*t4.*t9.*t13.*t18-V.*dr.*h.*m.*phidot.*t3.*t5.*t9.*t13.*t18-V.*dr.*h.*m.*t2.*t4.*t5.*t13.*t18.*theta_Rdot;
phiddot = (et1+et2)./(I11+m.*t8);
end
