function B_lin = B_matrix(I11,V,df,dr,h,m,phi,theta_F,theta_R)
%B_matrix
%    B_lin = B_matrix(I11,V,DF,DR,H,M,PHI,theta_F,theta_R)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    12-Jun-2024 18:29:18

t2 = cos(phi);
t3 = cos(theta_F);
t4 = cos(theta_R);
t5 = sin(theta_F);
t6 = sin(theta_R);
t7 = df+dr;
t8 = df.^2;
t9 = dr.^2;
t10 = h.^2;
t11 = t2.^2;
t12 = t2.^3;
t13 = t2.^5;
t14 = t3.^2;
t15 = t4.^2;
t16 = t4.^3;
t18 = t4.^5;
t20 = m.*t10;
t21 = 1.0./t7.^2;
t17 = t15.^2;
t19 = 1.0./t14;
t22 = I11+t20;
t23 = -t15;
t24 = t11.*t15;
t25 = 1.0./t22;
t26 = t23+t24+1.0;
t27 = 1.0./t26.^(5.0./2.0);
et1 = h.*m.*t2.*t6.*t8.*t14+df.*dr.*h.*m.*t2.*t6.*t14+h.*m.*t2.*t3.*t4.*t5.*t9-h.*m.*t2.*t3.*t5.*t9.*t16.*2.0+h.*m.*t2.*t3.*t5.*t9.*t18-h.*m.*t2.*t6.*t8.*t14.*t15.*2.0+h.*m.*t3.*t5.*t9.*t12.*t16.*2.0+h.*m.*t2.*t6.*t8.*t14.*t17-h.*m.*t3.*t5.*t9.*t12.*t18.*2.0+h.*m.*t3.*t5.*t9.*t13.*t18+h.*m.*t6.*t8.*t12.*t14.*t15.*2.0-h.*m.*t6.*t8.*t12.*t14.*t17.*2.0+h.*m.*t6.*t8.*t13.*t14.*t17+df.*dr.*h.*m.*t2.*t3.*t4.*t5-df.*dr.*h.*m.*t2.*t3.*t5.*t16.*2.0+df.*dr.*h.*m.*t2.*t3.*t5.*t18+df.*dr.*h.*m.*t3.*t5.*t12.*t16.*2.0-df.*dr.*h.*m.*t2.*t6.*t14.*t15.*2.0-df.*dr.*h.*m.*t3.*t5.*t12.*t18.*2.0+df.*dr.*h.*m.*t2.*t6.*t14.*t17+df.*dr.*h.*m.*t3.*t5.*t13.*t18;
et2 = df.*dr.*h.*m.*t6.*t12.*t14.*t15.*2.0-df.*dr.*h.*m.*t6.*t12.*t14.*t17.*2.0+df.*dr.*h.*m.*t6.*t13.*t14.*t17;
mt1 = [0.0,1.0,t19.*t21.*t25.*t27.*(et1+et2),0.0,0.0,0.0,0.0,t19.*t21.*t25.*t27.*(V.*h.*m.*t2.*t4.*t9-V.*h.*m.*t2.*t9.*t16.*2.0+V.*h.*m.*t2.*t9.*t18+V.*h.*m.*t9.*t12.*t16.*2.0-V.*h.*m.*t9.*t12.*t18.*2.0+V.*h.*m.*t9.*t13.*t18+V.*df.*dr.*h.*m.*t2.*t4-V.*df.*dr.*h.*m.*t2.*t16.*2.0+V.*df.*dr.*h.*m.*t2.*t18+V.*df.*dr.*h.*m.*t12.*t16.*2.0-V.*df.*dr.*h.*m.*t12.*t18.*2.0+V.*df.*dr.*h.*m.*t13.*t18),1.0,0.0,0.0,0.0];
mt2 = [t19.*t21.*t25.*t27.*(V.*h.*m.*t4.*t8.*t12.*t14-V.*h.*m.*t8.*t12.*t14.*t16+V.*h.*m.*t8.*t13.*t14.*t16+V.*df.*dr.*h.*m.*t4.*t12.*t14-V.*df.*dr.*h.*m.*t12.*t14.*t16+V.*df.*dr.*h.*m.*t13.*t14.*t16-V.*h.*m.*t2.*t3.*t5.*t6.*t9-V.*df.*dr.*h.*m.*t2.*t3.*t5.*t6+V.*h.*m.*t2.*t3.*t5.*t6.*t9.*t15+V.*h.*m.*t3.*t5.*t6.*t9.*t12.*t23+V.*df.*dr.*h.*m.*t2.*t3.*t5.*t6.*t15+V.*df.*dr.*h.*m.*t3.*t5.*t6.*t12.*t23),0.0,1.0];
B_lin = reshape([mt1,mt2],5,3);
end
